**Варіант 3**

**Завдання:** 1, 3, 6, 7, 8,
11, 16, 18,
19

In [81]:
import time
import numpy as np
import random

1) Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [82]:
def create_diagonal_matrix(n):
    start_time = time.time()

    matrix = np.zeros((n, n), dtype=int)
    np.fill_diagonal(matrix, np.arange(1, n + 1))

    end_time = time.time()

    return matrix, end_time - start_time


def create_diagonal_matrix_no_numpy(n):

    start_time = time.time()

    matrix = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        matrix[i][i] = i + 1

    end_time = time.time()

    return matrix, end_time - start_time

n = 1000

matrix, time_numpy = create_diagonal_matrix(n)

print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")
#print(matrix)

matrix, time_no_numpy = create_diagonal_matrix_no_numpy(n)

print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")
#print(matrix)

Час виконання з NumPy: 0.000993 секунд
Час виконання без NumPy: 0.024921 секунд


3) Вводяться 4 числа n, m, r, c. Вивести масив розміру
n×m, в якому в кожному рядку з номером r і в кожному стовпчику з
номером c стоять 0, а інші елементи дорівнюють 1

In [83]:
def create_matrix_with_zeros(n, m, r, c):

    start_time = time.time()

    matrix = np.ones((n, m), dtype=int)
    matrix[r, :] = 0
    matrix[:, c] = 0

    end_time = time.time()

    return matrix, end_time - start_time


def create_matrix_with_zeros_no_numpy(n, m, r, c):
    start_time = time.time()

    matrix = [[1 for _ in range(m)] for _ in range(n)]
    for i in range(n):
        matrix[i][c] = 0
    for j in range(m):
        matrix[r][j] = 0

    end_time = time.time()

    return matrix, end_time - start_time


n = 1000
m = 1000
r = 2
c = 1

matrix, time_numpy = create_matrix_with_zeros(n, m, r, c)

print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")
#print(matrix)

matrix, time_no_numpy = create_matrix_with_zeros_no_numpy(n, m, r, c)

print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")
#print(matrix)

Час виконання з NumPy: 0.000997 секунд
Час виконання без NumPy: 0.023925 секунд


6) З клавіатури вводиться масив. Замінити всі ненульові
елементи на –1.

In [84]:
def replace_non_zero_elements(array):
    start_time = time.time()

    array[array != 0] = -1

    end_time = time.time()

    return array, end_time - start_time

def replace_non_zero_elements_no_numpy(array):
    start_time = time.time()

    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] != 0:
                array[i][j] = -1

    end_time = time.time()

    return array, end_time - start_time

array = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])

array, time_numpy = replace_non_zero_elements(array)

print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")
print(array)

array = [[1, 2, 3], [4, 0, 6], [7, 8, 9]]
array, time_no_numpy = replace_non_zero_elements_no_numpy(array)

print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")
print(array)

Час виконання з NumPy: 0.000000 секунд
[[-1 -1 -1]
 [-1  0 -1]
 [-1 -1 -1]]
Час виконання без NumPy: 0.000000 секунд
[[-1, -1, -1], [-1, 0, -1], [-1, -1, -1]]


7) З клавіатури вводиться масив. Замінити всі нульові елементи на –1.

In [85]:
def replace_non_zero_elements(array):
    start_time = time.time()

    array[array == 0] = -1

    end_time = time.time()

    return array, end_time - start_time

def replace_non_zero_elements_no_numpy(array):
    start_time = time.time()

    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == 0:
                array[i][j] = -1

    end_time = time.time()

    return array, end_time - start_time

array = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])

array, time_numpy = replace_non_zero_elements(array)

print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")
print(array)

array = [[1, 2, 3], [4, 0, 6], [7, 8, 9]]
array, time_no_numpy = replace_non_zero_elements_no_numpy(array)

print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")
print(array)

Час виконання з NumPy: 0.000000 секунд
[[ 1  2  3]
 [ 4 -1  6]
 [ 7  8  9]]
Час виконання без NumPy: 0.000000 секунд
[[1, 2, 3], [4, -1, 6], [7, 8, 9]]


8. З клавіатури вводиться масив. Підрахувати в ньому
кількість нульових та ненульових елементів.

In [86]:
def count_zeros_and_nonzeros():
  
    array = list(map(int, input("Введіть елементи масиву через пробіл: ").split()))
    
    count_zeros = 0
    count_nonzeros = 0
    start_time = time.time()
    
    for element in array:
        if element == 0:
              count_zeros += 1
        else:
              count_nonzeros += 1
    end_time = time.time()
    print(f"Час виконання: {end_time - start_time:.6f} секунд")
    
    return count_zeros, count_nonzeros

def count_zeros_and_nonzeros_numpy():
    array = np.array(list(map(int, input("Введіть елементи масиву через пробіл: ").split())))
    
    start_time = time.time()
    
    count_zeros = np.count_nonzero(array == 0)
    count_nonzeros = len(array) - count_zeros
    
    end_time = time.time()
    print(f"Час виконання: {end_time - start_time:.6f} секунд")
    
    return count_zeros, count_nonzeros

count_zeros, count_nonzeros = count_zeros_and_nonzeros()

print(f"Кількість нульових елементів: {count_zeros}")
print(f"Кількість ненульових елементів: {count_nonzeros}")

count_zeros, count_nonzeros = count_zeros_and_nonzeros_numpy()

print(f"Кількість нульових елементів numpy: {count_zeros}")
print(f"Кількість ненульових елементів numpy: {count_nonzeros}")

Введіть елементи масиву через пробіл: 1 0 10 0 0 0 0 0 0 0 0 0 0 10 10 0 0 0 0 0 1 0 0 0 1 0 0 0
Час виконання: 0.000000 секунд
Кількість нульових елементів: 22
Кількість ненульових елементів: 6
Введіть елементи масиву через пробіл: 1 0 10 0 0 0 0 0 0 0 0 0 0 10 10 0 0 0 0 0 1 0 0 0 1 0 0 0
Час виконання: 0.000000 секунд
Кількість нульових елементів numpy: 22
Кількість ненульових елементів numpy: 6


11) Створити масив одиниць розміром n×n та додати до нього «рамку», що утворюється з 0

In [87]:
import numpy as np

def create_array_with_frame(n):
    
    start_time = time.time()
    
    array = np.ones((n, n), dtype=int)
    array[0, :] = 0
    array[-1, :] = 0
    array[:, 0] = 0
    array[:, -1] = 0
    
    end_time = time.time()
    print(f"Час виконання: {end_time - start_time:.20f} секунд")
    
    return array

def create_array_with_frame_no_numpy(n):
    
    start_time = time.time()
    
    array = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(1, n - 1):
        for j in range(1, n - 1):
            array[i][j] = 1
            
    end_time = time.time()
    print(f"Час виконання: {end_time - start_time:.20f} секунд")
    
    return array

n = 100

array = create_array_with_frame_no_numpy(n)
for row in array:
    print(row)

# numpy
array = create_array_with_frame(n)

print(array)



Час виконання: 0.00099849700927734375 секунд
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

16) Заповнити вектор значеннями від 0 до n. Всі значення,
що більші за n/4 та менші за 3n/4 замінити нулями.

In [88]:
def create_vector_with_zeros(n):
    start_time = time.time()

    vector = np.arange(n)
    vector[(vector > n / 4) & (vector < 3 * n / 4)] = 0

    end_time = time.time()

    return vector, end_time - start_time


def create_vector_with_zeros_no_numpy(n):

    start_time = time.time()

    vector = []
    for i in range(n):
        if i > n / 4 and i < 3 * n / 4:
            vector.append(0)
        else:
            vector.append(i)

    end_time = time.time()

    return vector, end_time - start_time

n = 10000

vector, time_numpy = create_vector_with_zeros(n)

print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")
print(vector)

vector, time_no_numpy = create_vector_with_zeros_no_numpy(n)

print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")
print(vector)

Час виконання з NumPy: 0.000000 секунд
[   0    1    2 ... 9997 9998 9999]
Час виконання без NumPy: 0.001002 секунд
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198

18. Згенерувати вектор з n випадкових чисел в діапазоні
від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [89]:
def generate_unique_numbers(n):
    start_time = time.time()

    vector = np.random.randint(0, 100, n)
    unique_numbers = np.unique(vector).size

    end_time = time.time()

    return vector, unique_numbers, end_time - start_time

def generate_unique_numbers_no_numpy(n):
    start_time = time.time()

    vector = []
    for _ in range(n):
        vector.append(random.randint(0, 99))
    unique_numbers = len(set(vector))

    end_time = time.time()

    return vector, unique_numbers, end_time - start_time

n = 100000

vector, unique_numbers, time_numpy = generate_unique_numbers(n)

print(f"Кількість унікальних чисел: {unique_numbers}")
print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")

vector, unique_numbers, time_no_numpy = generate_unique_numbers_no_numpy(n)

print(f"Кількість унікальних чисел: {unique_numbers}")
print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")

Кількість унікальних чисел: 100
Час виконання з NumPy: 0.003986 секунд
Кількість унікальних чисел: 100
Час виконання без NumPy: 0.041860 секунд


19. Згенерувати вектор із n елементів, що рівномірно
розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не
включені. Значення вивести до 3 знаків після коми.

In [90]:
def generate_random_vector(n):

    start_time = time.time()

    vector = np.random.uniform(0, 1, n)
    vector = np.round(vector, 3)

    end_time = time.time()

    return vector, end_time - start_time

def generate_random_vector_no_numpy(n):
    start_time = time.time()

    vector = []
    for _ in range(n):
        vector.append(round(random.uniform(0, 1), 3))

    end_time = time.time()

    return vector, end_time - start_time


# Приклад використання

n = 100000

vector, time_numpy = generate_random_vector(n)

print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")
print(vector)

vector, time_no_numpy = generate_random_vector_no_numpy(n)

print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")
print(vector)

Час виконання з NumPy: 0.000997 секунд
[0.554 0.194 0.063 ... 0.156 0.167 0.178]
Час виконання без NumPy: 0.056814 секунд
[0.529, 0.006, 0.841, 0.747, 0.203, 0.463, 0.728, 0.15, 0.199, 0.404, 0.118, 0.29, 0.506, 0.668, 0.309, 0.039, 0.77, 0.414, 0.183, 0.715, 0.485, 0.186, 0.492, 0.846, 0.988, 0.419, 0.452, 0.424, 0.528, 0.763, 0.062, 0.868, 0.247, 0.215, 0.636, 0.471, 0.84, 0.359, 0.502, 0.03, 0.093, 0.312, 0.096, 0.711, 0.693, 0.902, 0.663, 0.803, 0.471, 0.131, 0.732, 0.465, 0.094, 0.198, 0.932, 0.704, 0.85, 0.078, 0.592, 0.042, 0.091, 0.341, 0.706, 0.58, 0.07, 0.34, 0.855, 0.699, 0.944, 0.899, 0.177, 0.512, 0.353, 0.247, 0.015, 0.965, 0.666, 0.949, 0.513, 0.943, 0.657, 0.369, 0.847, 0.971, 0.699, 0.545, 0.257, 0.115, 0.775, 0.35, 0.365, 0.813, 0.173, 0.347, 0.683, 0.073, 0.935, 0.278, 0.413, 0.544, 0.017, 0.975, 0.436, 0.751, 0.799, 0.843, 0.282, 0.545, 0.651, 0.966, 0.021, 0.98, 0.966, 0.419, 0.853, 0.595, 0.763, 0.743, 0.417, 0.646, 0.296, 0.811, 0.809, 0.788, 0.035, 0.969, 0.879,

\begin{cases}x_{1} + 2x_{2} + 3x_{3} + 4x_{4} = 5 \\2x_{1} + x_{2} + 2x_{3} + 3x_{4} = 1\\3x_{1} + 2x_{2} + x_{3} + 2x_{4} = 1\\4x_{1} + 3x_{2} + 2x_{3} + x_{4} = -5\end{cases}

In [91]:
def cramer_method(A, b):

    det_A = np.linalg.det(A)
    print(det_A)
    
    print(np.insert(np.delete(A, 0, 1), 0, b, axis=1))
    det_A_x = np.linalg.det(np.insert(np.delete(A, 0, 1), 0, b, axis=1))
    print(det_A_x)
    det_A_y = np.linalg.det(np.insert(np.delete(A, 1, 1), 1, b, axis=1))
    print(det_A_y)
    det_A_z = np.linalg.det(np.insert(np.delete(A, 2, 1), 2, b, axis=1))
    print(det_A_z)
    det_A_f = np.linalg.det(np.insert(np.delete(A, 3, 1), 3, b, axis=1))
    print(det_A_z)

    x = det_A_x / det_A
    y = det_A_y / det_A
    z = det_A_z / det_A
    f = det_A_f / det_A

    return np.array([x, y, z, f])

A = np.array([[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1, 2], [4 ,3 ,2 , 1]])
b = np.array([5, 1, 1, -5])

solution_cramer = cramer_method(A, b)

print("Розв'язок за допомогою формул Крамера:", solution_cramer)

solution_matrix_multiplication = np.linalg.solve(A, b)

print("Перевірка за допомогою матричного множення:", solution_matrix_multiplication)

inverse_A = np.linalg.inv(A)

solution_inverse_matrix = np.dot(inverse_A, b)

print("Перевірка за допомогою оберненої матриці:", solution_inverse_matrix)


solution_linalg_solve = np.linalg.solve(A, b)

print("Перевірка за допомогою numpy.linalg.solve():", solution_linalg_solve)

print("Порівняння всіх рішень:", np.allclose(solution_cramer, solution_matrix_multiplication), np.allclose(solution_cramer, solution_inverse_matrix), np.allclose(solution_cramer, solution_linalg_solve))

-19.999999999999996
[[ 5  2  3  4]
 [ 1  1  2  3]
 [ 1  2  1  2]
 [-5  3  2  1]]
40.0
-40.000000000000014
59.999999999999986
59.999999999999986
Розв'язок за допомогою формул Крамера: [-2.  2. -3.  3.]
Перевірка за допомогою матричного множення: [-2.  2. -3.  3.]
Перевірка за допомогою оберненої матриці: [-2.  2. -3.  3.]
Перевірка за допомогою numpy.linalg.solve(): [-2.  2. -3.  3.]
Порівняння всіх рішень: True True True


$$
3)\:2(A - B)(A^{2} + B)
$$

A = \begin{bmatrix}5&1&7\\-10&-2&1\\0&1&2\end{bmatrix} B = \begin{bmatrix}2&4&1\\3&1&0\\7&2&1\end{bmatrix}

In [94]:
def matrix_expression(A, B):
    start_time = time.time()

    C = 2 * (A - B) * (np.dot(A, A) + B)

    end_time = time.time()

    return C, end_time - start_time


def matrix_expression_no_numpy(A, B):
    start_time = time.time()

    C = [[0 for _ in range(len(A[0]))] for _ in range(len(A))]

    for i in range(len(A)):
        for j in range(len(A[0])):
            for k in range(len(A[0])):
                C[i][j] += 2 * (A[i][k] - B[i][k]) * (A[k][j] + B[k][j])

    end_time = time.time()

    return C, end_time - start_time

A = np.array([[5, 1, 7], [-10, -2, 1], [0, 1, 2]])
B = np.array([[2, 4, 1], [3, 1, 0], [7, 2, 1]])

C_numpy, time_numpy = matrix_expression(A, B)

print(f"Час виконання з NumPy: {time_numpy:.6f} секунд")
print(C_numpy)

C_no_numpy, time_no_numpy = matrix_expression_no_numpy(A, B)

print(f"Час виконання без NumPy: {time_no_numpy:.6f} секунд")
print(C_no_numpy)

Час виконання з NumPy: 0.000000 секунд
[[ 102  -84  612]
 [ 702   24 -140]
 [  42   -4   12]]
Час виконання без NumPy: 0.000000 секунд
[[168, 72, 78], [-126, -118, -208], [-70, -62, -108]]
